---


- name: install Node Exporter binaries
  become: yes
  shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64
    sudo useradd --no-create-home node_exporter



- name: Configure a service
  become: yes
  template:
    src: "files/node-exporter.service"
    dest: "/etc/systemd/system/node-exporter.service"


- name: Configure systemd
  become: yes
  shell: |
   systemctl daemon-reload
   systemctl enable node-exporter
   systemctl start node-exporter
